// <auto-generated />
using System;
using DSU_Grupp3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSU_Grupp3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DSU_Grupp3.Models.DTO.DeSoDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeSoDTOs");
                });

            modelBuilder.Entity("DSU_Grupp3.Models.DTO.DesoCodeInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeSoDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DesoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicipalityCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PopulationFemales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PopulationMales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPopulation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalVaccinated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VaccinatedFemales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VaccinatedMales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VaccinatedOtherGender")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeSoDTOId");

                    b.ToTable("DesoCodeInformation");
                });

            modelBuilder.Entity("DSU_Grupp3.Models.DTO.DesoCodeInformation", b =>
                {
                    b.HasOne("DSU_Grupp3.Models.DTO.DeSoDTO", null)
                        .WithMany("Areas")
                        .HasForeignKey("DeSoDTOId");
                });

            modelBuilder.Entity("DSU_Grupp3.Models.DTO.DeSoDTO", b =>
                {
                    b.Navigation("Areas");
                });
#pragma warning restore 612, 618
        }
    }
}
